vtk_module(vtkIONetCDF
  GROUPS
    StandAlone
  DEPENDS
    vtknetcdf
    vtkCommonDataModel
    vtkCommonSystem
    vtkIOCore
  PRIVATE_DEPENDS
    vtksys
  COMPILE_DEPENDS
    vtknetcdf
    vtknetcdfcxx
  TEST_DEPENDS
    vtkCommonExecutionModel
    vtkRenderingOpenGL
    vtkTestingRendering
    vtkInteractionStyle
  )
