vtk_module(vtkIONetCDF
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonDataModel
    vtkCommonSystem
    vtkIOCore
  COMPILE_DEPENDS
    vtkNetCDF
    vtkNetCDFCXX
  PRIVATE_DEPENDS
    vtksys
  TEST_DEPENDS
    vtkCommonExecutionModel
    vtkRenderingOpenGL
    vtkTestingRendering
    vtkInteractionStyle
  )
